# Generated by Django 5.2.12 on 2026-03-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='booking_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
