# Generated by Django 5.2.12 on 2026-03-25 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom en français')),
                ('wilaya_number', models.IntegerField(unique=True, verbose_name='رقم الولاية')),
                ('region', models.CharField(max_length=50, verbose_name='المنطقة')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'مدينة',
                'verbose_name_plural': 'المدن',
                'ordering': ['wilaya_number'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(verbose_name='معرف المالك')),
                ('brand', models.CharField(max_length=50, verbose_name='الماركة')),
                ('model', models.CharField(max_length=50, verbose_name='الموديل')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='السنة')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='اللون')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='رقم اللوحة')),
                ('vehicle_type', models.CharField(choices=[('car', 'سيارة'), ('van', 'سيارة أجرة'), ('bus', 'حافلة')], default='car', max_length=20, verbose_name='نوع المركبة')),
                ('seats', models.IntegerField(verbose_name='عدد المقاعد')),
                ('has_air_conditioning', models.BooleanField(default=False, verbose_name='مكيف هواء')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='واي فاي')),
                ('has_smoking_allowed', models.BooleanField(default=False, verbose_name='مسموح التدخين')),
                ('has_pets_allowed', models.BooleanField(default=False, verbose_name='مسموح الحيوانات')),
                ('has_luggage_space', models.BooleanField(default=True, verbose_name='مساحة للأمتعة')),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مركبة',
                'verbose_name_plural': 'المركبات',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField(verbose_name='معرف السائق')),
                ('vehicle_id', models.IntegerField(verbose_name='معرف المركبة')),
                ('departure_datetime', models.DateTimeField(verbose_name='تاريخ ووقت الانطلاق')),
                ('arrival_datetime', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت الوصول')),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر لكل مقعد')),
                ('total_seats', models.IntegerField(verbose_name='إجمالي المقاعد')),
                ('available_seats', models.IntegerField(verbose_name='المقاعد المتاحة')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('intermediate_stops', models.JSONField(blank=True, default=list, verbose_name='محطات وسيطة')),
                ('gender_preference', models.CharField(default='any', max_length=20, verbose_name='تفضيل الجنس')),
                ('smoking_allowed', models.BooleanField(default=False, verbose_name='مسموح التدخين')),
                ('chat_preference', models.CharField(default='any', max_length=20, verbose_name='تفضيل الدردشة')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('completed', 'منتهية'), ('cancelled', 'ملغاة')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='trajet_app.city', verbose_name='مدينة الوصول')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='trajet_app.city', verbose_name='مدينة الانطلاق')),
            ],
            options={
                'verbose_name': 'رحلة',
                'verbose_name_plural': 'الرحلات',
                'indexes': [models.Index(fields=['departure_city', 'arrival_city', 'departure_datetime', 'status'], name='trajet_app__departu_be4fc6_idx'), models.Index(fields=['driver_id'], name='trajet_app__driver__0b26ff_idx'), models.Index(fields=['status'], name='trajet_app__status_37130f_idx')],
            },
        ),
    ]
