# Generated by Django 5.2.12 on 2026-04-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['wilaya_number'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='ride',
            options={'verbose_name': 'Ride', 'verbose_name_plural': 'Rides'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Name in Arabic'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_fr',
            field=models.CharField(max_length=100, verbose_name='Name in French'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(max_length=50, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='city',
            name='wilaya_number',
            field=models.IntegerField(unique=True, verbose_name='Wilaya Number'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='trajet_app.city', verbose_name='Arrival City'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrival Date and Time'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='available_seats',
            field=models.IntegerField(verbose_name='Available Seats'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='chat_preference',
            field=models.CharField(default='any', max_length=20, verbose_name='Chat Preference'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='trajet_app.city', verbose_name='Departure City'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_datetime',
            field=models.DateTimeField(verbose_name='Departure Date and Time'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver_id',
            field=models.IntegerField(verbose_name='Driver ID'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='gender_preference',
            field=models.CharField(default='any', max_length=20, verbose_name='Gender Preference'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='intermediate_stops',
            field=models.JSONField(blank=True, default=list, verbose_name='Intermediate Stops'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Seat'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='smoking_allowed',
            field=models.BooleanField(default=False, verbose_name='Smoking Allowed'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='total_seats',
            field=models.IntegerField(verbose_name='Total Seats'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle_id',
            field=models.IntegerField(verbose_name='Vehicle ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_air_conditioning',
            field=models.BooleanField(default=False, verbose_name='Air Conditioning'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_luggage_space',
            field=models.BooleanField(default=True, verbose_name='Luggage Space'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_pets_allowed',
            field=models.BooleanField(default=False, verbose_name='Pets Allowed'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_smoking_allowed',
            field=models.BooleanField(default=False, verbose_name='Smoking Allowed'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='WiFi'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, verbose_name='License Plate'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner_id',
            field=models.IntegerField(verbose_name='Owner ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(verbose_name='Number of Seats'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('van', 'Van'), ('bus', 'Bus')], default='car', max_length=20, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.CreateModel(
            name='Stopover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Stop Order')),
                ('price_to_stop', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trajet_app.city', verbose_name='Stop City')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopovers', to='trajet_app.ride')),
            ],
            options={
                'verbose_name': 'Stopover',
                'verbose_name_plural': 'Stopovers',
                'ordering': ['order'],
            },
        ),
    ]
