# Generated by Django 6.0.3 on 2026-04-03 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_refreshtoken_usersession_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='driver_license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_card_photo',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Numéro algérien (ex: 0550123456)', regex='^0[567]\\d{8}$')]),
        ),
    ]
